# GLOBAL CONFIGURATION

spring:
  application.name: service-two
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
  jackson.serializationindent_output: true

info:
  component: Service-Two
  artifact: service-two
  version: 5.0.0

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

management:
  contextPath: /actuator

server:
  contextPath: /
  port: 8084

---
#DEFAULT CONFIGURATION
spring:
  profiles: default
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  cloud:
    consul.enabled: false
    loadbalancer.ribbon.enabled: false
  h2.console:
    enabled: true
    path: /h2
  datasource:
    url: jdbc:h2:mem:service-two
    driverClassName: org.h2.Driver
    username: mudigal
    password: mudigal
    driver-class-name: org.h2.Driver
  jpa.database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org.springframework.web: WARN
    com.mudigal.one: INFO

---
# DOCKER CONFIGURATION
spring:
  profiles: docker
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        hostName: service-two
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        healthCheckPath: ${management.contextPath}/health
        healthCheckInterval: 15s
    loadbalancer.ribbon.enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://service-two-db/service-two?createDatabaseIfNotExist=true
    username: service-two
    password: service-two
  jpa:
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  rabbitmq:
    host: rabbit
    port: 5672
    username: mudigal
    password: mudigal
    virtualHost: /

logstash:
  servers: logstash:5000

logging:
  file: service-two-application.log
  pattern:
    file: "%d %-5level [%thread] %logger{0}: %msg%n"
  level:
    org.springframework.web: WARN
    com.mudigal.two: DEBUG
    org.hibernate: WARN